# Generated by Django 6.0.4 on 2026-05-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, max_length=200)),
                ('message', models.TextField()),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('degree', models.CharField(max_length=200)),
                ('institution', models.CharField(max_length=200)),
                ('institution_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_year', models.IntegerField()),
                ('end_year', models.IntegerField(blank=True, help_text='Leave blank if ongoing', null=True)),
                ('is_ongoing', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_year', 'order'],
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=150)),
                ('company', models.CharField(max_length=150)),
                ('company_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, help_text='Leave blank if current', null=True)),
                ('is_current', models.BooleanField(default=False)),
                ('description', models.TextField(help_text='Use newlines; each line becomes a bullet point')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('title', models.CharField(help_text='e.g. Web Application Developer', max_length=150)),
                ('tagline', models.CharField(help_text='Short motivating phrase', max_length=255)),
                ('bio', models.TextField(help_text='Professional summary for About Me section')),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='profile/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='cover/')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('website_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('location', models.CharField(blank=True, max_length=100)),
                ('available_for_work', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Profile',
                'verbose_name_plural': 'Profile',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly identifier, e.g. my-cool-project', unique=True)),
                ('tagline', models.CharField(blank=True, help_text='One-liner shown on card', max_length=255)),
                ('description', models.TextField(help_text='Full description shown on project detail page')),
                ('thumbnail', models.ImageField(help_text='Full-height screenshot for hover scroll preview (tall image recommended)', upload_to='projects/')),
                ('tech_stack', models.CharField(help_text='Comma-separated list, e.g. Django, PostgreSQL, React', max_length=500)),
                ('live_url', models.URLField(blank=True, help_text='Leave blank to hide button')),
                ('github_url', models.URLField(blank=True, help_text='Leave blank to hide button')),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Download CV', max_length=100)),
                ('file', models.FileField(help_text='Upload PDF file', upload_to='resume/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Resume / CV',
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('database', 'Database'), ('devops', 'DevOps & Tools'), ('other', 'Other')], default='other', max_length=20)),
                ('proficiency', models.IntegerField(default=80, help_text='Proficiency percentage 0–100 (used for progress bar display)')),
                ('order', models.PositiveIntegerField(default=0)),
                ('icon_class', models.CharField(blank=True, help_text='Optional: a CSS class or emoji for the skill icon', max_length=80)),
            ],
            options={
                'ordering': ['category', 'order', 'name'],
            },
        ),
    ]
